
language: ruby
rvm:
- 2.0.0
script:
- psql -c 'create database test_postgres;' -U postgres
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
bundler_args: --binstubs=./bundler_stubs

deploy:
  provider: heroku
  api_key:
    secure: ####
  app: nbarnes
  on:
    repo: nbarnes/photo_manager
  run:
    - 'rake db:migrate'
